# Generated by Django 3.1.4 on 2020-12-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
